apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml: |-
    ---
    {{- $baseConfig := .Files.Get "mimir.yaml" | fromYaml }}
    {{- $mergedConfig := merge  .Values.mimirConfig $baseConfig }}
    {{- toYaml $mergedConfig | nindent 4 }}