apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
  storageClassName: {{ .Values.storageClassName }}