name: Build and Serve Helm Charts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0

    - name: Build all Helm charts
      run: |
        mkdir -p packaged/

        for chart in `ls . | grep -v packaged`; do
          helm package $chart -d packaged/
        done

    - name: Create Helm repo index
      run: helm repo index packaged --url https://damfle.github.io/charts

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        publish_dir: ./packaged